### PR TITLE
add osmenrich to put changesets data into database

### PR DESCRIPTION
**Pull request by meomancer**
hi @timlinux 
here is the PR to enrich database with changeset
The process on enrich are:
1. Check database is ready (by parsing mapping.yml
2. If ready, create column for necessary field

The inserting data process is done in loop for every 120 secs (same like osmupdate). The process area:
1. Getting database with empty changeset and use OSM API to get it
2. Get diff file on import done and change and set it into database
when save into database, it will check changeset_timestamp to check the database is old or not

Here is logs from docker_osmenrich:
Selection_124

here is database that already enriched
Selection_123

### CODE REVIEW

**Comment by timlinux** [comment]
Ah man, that is nice work @meomancer ! Only comment I have to make is that we need to update README at top level of the repo and add a README  in the OSMENRICH folder to explain architecture, purpose and usage of OSMENRICH.

Can you work with Janusz to get this deployed on staging?

Also, how will if backfill data if you have a running db? Do you expect any issues if we hit the OSM API 650k tiimes? Maybe we need to rate-limit it somehow?

**Comment by meomancer** [comment]
hi @timlinux 
we are using 20 batch data perhit, so we expect to have 30k for earth database
and also i tried mine (but it was just 10k data), and do it around 3-5 times testing (by drop database, so need to rerun it), and the api is still quite stable

and also, when API is down, it will skip and run the next batch
so, enrich will trying it again in next loop

**Comment by meomancer** [comment]
and also @timlinux 
i haven't create the image for osmenrich, still using build
HS is using images from docker osm
should we upload image for osmenrich? like imposm and osmupdate?

**Comment by timlinux** [comment]
> and also @timlinux
> i haven't create the image for osmenrich, still using build
> HS is using images from docker osm
> should we upload image for osmenrich? like imposm and osmupdate?

Yes please.

**Comment by amenk** [comment]
No readme yet, wondering what this is about. It sounds interesting, though :)

**Comment by meomancer** [comment]
hi @amenk 
readme added into the plugin

**Comment by NyakudyaA** [comment]
@meomancer just one comment. The OSM enrich wait's for the DB to start but ideally, it should also check if the public schema has been populated because in most cases if the pdf import take time then the enrich would still try to create those tables ie

Screen Shot 2020-01-14 at 16 02 40

**Pull request merged**
